# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculo', models.CharField(max_length=200, verbose_name='curriculo')),
                ('artigos', models.ManyToManyField(to='evento.ArtigoCientifico')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('evento_pricipal', models.CharField(max_length=200, verbose_name='evento principal')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
                ('data_hora_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data e hora do inicio do evento')),
                ('palavras_chave', models.CharField(max_length=200, verbose_name='encerramento do evento')),
                ('logotipo', models.CharField(max_length=40, verbose_name='logotipo')),
                ('cidade', models.CharField(max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='uf')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereco')),
                ('cep', models.CharField(max_length=15, verbose_name='cep')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=40, verbose_name='issn')),
                ('artigo_cientifico', models.ManyToManyField(to='evento.ArtigoCientifico')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data e hora da inscrica')),
                ('tipo_inscricao', models.CharField(choices=[('Professor', 'Professor'), ('Aluno', 'Aluno'), ('Profissional', 'Profissional')], max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15, verbose_name='cpf')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, verbose_name='cnpj')),
                ('razao_social', models.CharField(max_length=50, verbose_name='razao social')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='participantes',
            field=models.ManyToManyField(to='evento.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa'),
        ),
        migrations.AddField(
            model_name='autor',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(to='evento.Autor'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.EventoCientifico'),
        ),
    ]
